name: 'Http://www.Jijunape.com'
analytics: {}
github: true
description: 'jijunape for everything  '
author:
  name: Jose A Menendez
  email: jijunape@mac.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/670374ca-24ea-4db2-8f24-b0cee691bb52.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/670374ca-24ea-4db2-8f24-b0cee691bb52.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
layout_spectrum: 1
color:
  lightness: 0.3764769
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  saturation: 0.5021482
  brandStrength: 0.9052759
  rhythmicContrast: 0.6417831
content_rating:
  adult: false
typography_spectrum: 0.2443609
opengraph: {}
title: jijunape
